version: '2'
services:
    demomicroserviceapp-app:
        image: demomicroserviceapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demomicroserviceapp-mysql:3306/demomicroserviceapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    demomicroserviceapp-mysql:
        extends:
            file: mysql.yml
            service: demomicroserviceapp-mysql
